import {Schema, Types, model } from "mongoose";

const HistoriesSchema = new Schema(
    {
        date:{
            type: Date
        },
        file:{

        }
    }
)
/*
•	ELABORAR MANUAL DE CALIDAD PARA NUESTRA EMPRESA, ESE MANUAL DE CALIDAD SE PUEDE ELABORAR A ISO 9001, IEEE, CMMI
•	TENEMOS QUE DESCRIBIR LA MISION, VISION, SLOGAN, PATRONES DE DESARROLLO PARA LOS DISTINTOS 
PROYECTOS (TODOS ESTOS PUNTOS VIENEN A 
    ESTABLECER UN MARCO DE TRABAJO QUE OCUPA CADA EMPRESA PARA DESARROLLAR SU PROYECTO DE MANERA PARTICULAR)
*/